apiVersion: v1
kind: Service
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    k8s-app: kube-etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2379
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    k8s-app: kube-etcd
subsets:
- addresses:
  - ip: 10.0.0.5
    nodeName: 10.0.0.5
  - ip: 10.0.0.15
    nodeName: 10.0.0.15
  - ip: 10.0.0.20
    nodeName: 10.0.0.20
  ports:
  - name: http-metrics
    port: 2379
    protocol: TCP
