kind: ConfigMap
apiVersion: v1
metadata:
  name: mails
  namespace: prometheus
data:
  mail.tmpl: |
    {{ define "alert.html" }}
    <table border="1px" bordercolor="#000000" cellspacing="0px" style="border-collapse:collapse">
    <tr>
        <td>name</td>
        <td>event</td>
        <td>start</td>
        <td>end</td>
    </tr>
    {{ range $i, $alert := .Alerts }}
    <tr>
        <td> {{ index $alert.Annotations "policy" }} </td>
        <td> {{ index $alert.Annotations "description" }} </td>
        <td> {{ timeOffsetStr $alert.StartsAt "8h" "20060102 15:04:05"}} </td>
        <td> {{ timeOffsetStr $alert.EndsAt "8h" "20060102 15:04:05" }} </td>
    </tr>
    {{ end }}
    </table>
    {{ end }}
